#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate
#export DJANGO_SETTINGS_MODULE=main.settings
#python manage.py runserver 0.0.0.0:8000
daphne -b 0.0.0.0 -p 8000 main.asgi:application

