kind: ExternalService
name: reverse96-deploy
spec: 
  image: reverse_test:1.0
  image_pull_policy: Always # or default is IfNotPresent
  replicas: 1
  resources:
    memory: 100Mi
  env:
  - name: POSTGRESS_PASSWORD
  value: test123
  - name: POSTGRESS_HOST
  value: postgress
  


