version: "3"

services:
  redis:
    image: redis:alpine
    networks:
      - back
    ports:
      - "6379:6379"
  daphne:
    build: ./project
    image: "channel_prod:latest"
    working_dir: /src/
    command: bash -c "./migrate.sh;"
    command: daphne -b 0.0.0.0 -p 9542 main.asgi:application
    ports:
      - "9542:9542"
    env_file:
      - ./project/app_env
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
  worker:
    image: "channel_prod:latest"
    working_dir: /src/
    command: bash -c "python manage.py runworker 'file-upload'"
    env_file:
      - ./project/app_env
    networks:
      - front
      - back
    depends_on:
      - redis
    links:
      - redis
networks:
  front:
  back:
