name: learn-github-actions
on: push
jobs:
  check-super-lint:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checking our the code at current commit that triggers the workflow
        uses: actions/checkout@v3
      - name: Setup python environment # setting python environment to 3.x
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python --version
      - name: Install requirements # install application requirements
        run: pip install -r requirements.txt
      - name: Check Syntax # check code formatting
        run: pycodestyle --statistics .
      - name: Run Migrations # run migrations to create table in side car db container
        run: python manage.py migrate
      - name: Run Test # running tests
        run: python manage.py test
